easy_admin:
    design:
        menu:
            - label: 'Front'
            - { label: 'Homepage', route: 'homepage', icon: 'home', target: '_blank' }
            - { label: 'Dashboard', route: 'admin_dashboard', default: true }
    list:
        actions:
            - { name: 'sort', icon: 'arrows', label: '', css_class: 'btn-sort' }
            - { name: 'edit', icon: 'pencil', css_class: 'btn btn-primary' }
            - { name: 'delete', icon: 'trash', css_class: 'btn btn-danger' }
            - { name: 'show', icon: 'eye', css_class: 'btn btn-info' }
            - { name: 'new', icon: 'plus', css_class: 'btn btn-primary' }
