easy_admin:
    design:
        menu:
            - { label: 'Homepage', route: 'homepage', icon: 'home', target: '_blank', css_class: 'sidebar-menu-homepage' }
            - { label: 'Dashboard', route: 'admin_dashboard', default: true }
            -
                label: 'System'
                roles: ['ROLE_SUPER_ADMIN']
                    - { label: 'Cache', route: 'krg_easyadmin_cache_clear', icon: 'server' }
    list:
        actions:
            - { name: 'sort', icon: 'arrows-v', label: '', css_class: 'btn-sort' }
            - { name: 'edit', icon: 'edit', css_class: 'btn btn-primary' }
            - { name: 'delete', icon: 'trash', css_class: 'btn btn-danger' }
            - { name: 'show', icon: 'info-circle', css_class: 'btn btn-info' }
            - { name: 'new', icon: 'plus', css_class: 'btn btn-primary' }
