easy_admin:
    translation_domain: 'admin'
    design:
        templates:
            list: '@KRGEasyAdminExtension/default/list.html.twig'
            field_string: '@KRGEasyAdminExtension/default/field_string.html.twig'
            field_text: '@KRGEasyAdminExtension/default/field_string.html.twig'
            field_image: '@KRGEasyAdminExtension/default/field_image.html.twig'
        menu:
            - { label: 'menu.homepage', route: 'homepage', icon: 'home', target: '_blank', css_class: 'sidebar-menu-homepage', priority: 9999 }
            - { label: 'menu.dashboard', route: 'admin_dashboard', icon: 'dashboard', default: true, priority: 9000 }
            -
                label: 'menu.system'
                group: 'System'
                priority: 0
                roles: ['ROLE_SUPER_ADMIN']
                children:
                    - { label: 'menu.cache', route: 'krg_easyadmin_cache_clear', icon: 'server' }
    list:
        actions:
            - { name: 'sort', icon: 'arrows-v', label: '', css_class: 'btn-sort', priority: -1 }
            - { name: 'new', icon: 'plus', css_class: 'btn btn-primary' }
            - { name: 'edit', icon: 'edit', css_class: 'btn btn-primary',  priority: 9001 }
            - { name: 'delete', icon: 'trash', css_class: 'btn btn-danger', priority: 9002 }
