services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $googleAnalyticsId: '%krg_easyadmin_google_analytics_id%'
            $cacheDir: '%kernel.cache_dir%'
            $env: '%kernel.environment%'
            $webDir: '%kernel.root_dir%/web'
            $logoutUrlGenerator: '@security.logout_url_generator'

    KRG\EasyAdminExtensionBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
        calls:
                - [setContainer, ["@service_container"]]
        public: true

    KRG\EasyAdminExtensionBundle\Cache\:
        resource: '../../Cache'
        tags: ['kernel.event_suscriber']

    KRG\EasyAdminExtensionBundle\Form\Type\:
        resource: '../../Form/Type'
        tags: ['form.type']

    KRG\EasyAdminExtensionBundle\Widget\:
        resource: '../../Widget'
        tags: ['krg.easyadmin.widget']
        public: true

    KRG\EasyAdminExtensionBundle\Toolbar\:
        resource: '../../Toolbar'
        tags: [{name: 'krg.easyadmin.toolbar', priority: 1000}]
        public: true

    KRG\EasyAdminExtensionBundle\Twig\KrgEasyAdminTwigExtension:
        decorates: 'easyadmin.twig.extension'

    KRG\EasyAdminExtensionBundle\Twig\:
        resource: '../../Twig/*'
        tags: ['twig.extension']

    KRG\EasyAdminExtensionBundle\Configuration\:
        resource: '../../Configuration'
        tags: ['easyadmin.config_pass']

    KRG\EasyAdminExtensionBundle\Filter\:
        resource: '../../Filter'
        tags: ['kernel.event_suscriber']

    KRG\EasyAdminExtensionBundle\Configuration\ClassMetadataConfigPass:
        tags: [{name: 'easyadmin.config_pass', priority: 1000}]

    KRG\EasyAdminExtensionBundle\EventListener\EasyAdminSubscriber:
        tags: [ 'kernel.event_subscriber' ]

    KRG\EasyAdminExtensionBundle\Form\Extension\KrgEasyAdminExtension:
        tags: [{ name: 'form.type_extension', extended_type: 'Symfony\Component\Form\Extension\Core\Type\FormType' }]
        public: true
